# Systems and Teams {#sec-sys-team}

```{r message=FALSE}
#| label: fig-num-systems-each-step
#| layout-ncol: 2
#| echo: false
#| out-width: "100%"
#| fig-cap:
#| - Ingestion Systems
#| - Processing Systems
#| - Elementary indexes Systems
#| - Aggregation Systems
#| - Finalization Systems
#| - One or More Systems Handle One or More Steps

library(ggplot2)
library(dplyr)

df <- read.csv("./data/results.csv")[,10:20]

df <- df |> rename(
    ingestion = "Approximately.how.many.distinct.systems.exist.for.each.step.to.make.your.CPI...Data.ingestion.",
    processing = "Approximately.how.many.distinct.systems.exist.for.each.step.to.make.your.CPI...Data.processing.",
    elementary = "Approximately.how.many.distinct.systems.exist.for.each.step.to.make.your.CPI...Elementary.indexes.",
    aggregation = "Approximately.how.many.distinct.systems.exist.for.each.step.to.make.your.CPI...Aggregation.",
    finalization = "Approximately.how.many.distinct.systems.exist.for.each.step.to.make.your.CPI...Finalization.",
    same_system = "For.any.of.your.systems..is.it.the.case.that.the.same.system.handles.more.than.one.step.for.making.your.CPI.",
    ingestion_same = "Indicate.which.steps.are.handled.by.the.same.system..for.up.to.five.typical.systems...System.1..Data.ingestion.",
    processing_same = "Indicate.which.steps.are.handled.by.the.same.system..for.up.to.five.typical.systems...System.1..Data.processing.",
    elementary_same = "Indicate.which.steps.are.handled.by.the.same.system..for.up.to.five.typical.systems...System.1..Elementary.indexes.",
    aggregation_same = "Indicate.which.steps.are.handled.by.the.same.system..for.up.to.five.typical.systems...System.1..Aggregation.",
    finalization_same = "Indicate.which.steps.are.handled.by.the.same.system..for.up.to.five.typical.systems...System.1..Finalization."
    )
df[sapply(df, is.character)] <- lapply(df[sapply(df, is.character)], as.factor)

ggplot(subset(df, ingestion != ""), aes(y=ingestion)) + geom_bar(fill="#d5e8d4")
ggplot(subset(df, processing != ""), aes(y=processing)) + geom_bar(fill="#d5e8d4")
ggplot(subset(df, elementary != ""), aes(y=elementary)) + geom_bar(fill="#d5e8d4")
ggplot(subset(df, aggregation != ""), aes(y=aggregation)) + geom_bar(fill="#d5e8d4")
ggplot(subset(df, finalization != ""), aes(y=finalization)) + geom_bar(fill="#d5e8d4")
ggplot(subset(df, same_system != "N/A"), aes(x=same_system)) + geom_bar(fill="blue")
```

```{r message=FALSE}
#| echo: false
#| out-width: "100%"
#| fig-cap: Frequency of Steps Handled by the Same System

df <- read.csv("./data/results.csv")[,15:40]

df <- df |> rename(
    ingestion_1 = "Indicate.which.steps.are.handled.by.the.same.system..for.up.to.five.typical.systems...System.1..Data.ingestion."    ,
    processing_1 = "Indicate.which.steps.are.handled.by.the.same.system..for.up.to.five.typical.systems...System.1..Data.processing."   ,
    elementary_1 = "Indicate.which.steps.are.handled.by.the.same.system..for.up.to.five.typical.systems...System.1..Elementary.indexes.",
    aggregation_1 = "Indicate.which.steps.are.handled.by.the.same.system..for.up.to.five.typical.systems...System.1..Aggregation."       ,
    finalization_1 = "Indicate.which.steps.are.handled.by.the.same.system..for.up.to.five.typical.systems...System.1..Finalization."      ,
    ingestion_2 = "Indicate.which.steps.are.handled.by.the.same.system..for.up.to.five.typical.systems...System.2..Data.ingestion."    ,
    processing_2 = "Indicate.which.steps.are.handled.by.the.same.system..for.up.to.five.typical.systems...System.2..Data.processing."   ,
    elementary_2 = "Indicate.which.steps.are.handled.by.the.same.system..for.up.to.five.typical.systems...System.2..Elementary.indexes.",
    aggregation_2 = "Indicate.which.steps.are.handled.by.the.same.system..for.up.to.five.typical.systems...System.2..Aggregation."       ,
    finalization_2 = "Indicate.which.steps.are.handled.by.the.same.system..for.up.to.five.typical.systems...System.2..Finalization."      ,
    ingestion_3 = "Indicate.which.steps.are.handled.by.the.same.system..for.up.to.five.typical.systems...System.3..Data.ingestion."    ,
    processing_3 = "Indicate.which.steps.are.handled.by.the.same.system..for.up.to.five.typical.systems...System.3..Data.processing."   ,
    elementary_3 = "Indicate.which.steps.are.handled.by.the.same.system..for.up.to.five.typical.systems...System.3..Elementary.indexes.",
    aggregation_3 = "Indicate.which.steps.are.handled.by.the.same.system..for.up.to.five.typical.systems...System.3..Aggregation."       ,
    finalization_3 = "Indicate.which.steps.are.handled.by.the.same.system..for.up.to.five.typical.systems...System.3..Finalization."      ,
    ingestion_4 = "Indicate.which.steps.are.handled.by.the.same.system..for.up.to.five.typical.systems...System.4..Data.ingestion."    ,
    processing_4 = "Indicate.which.steps.are.handled.by.the.same.system..for.up.to.five.typical.systems...System.4..Data.processing."   ,
    elementary_4 = "Indicate.which.steps.are.handled.by.the.same.system..for.up.to.five.typical.systems...System.4..Elementary.indexes.",
    aggregation_4 = "Indicate.which.steps.are.handled.by.the.same.system..for.up.to.five.typical.systems...System.4..Aggregation."       ,
    finalization_4 = "Indicate.which.steps.are.handled.by.the.same.system..for.up.to.five.typical.systems...System.4..Finalization."      ,
    ingestion_5 = "Indicate.which.steps.are.handled.by.the.same.system..for.up.to.five.typical.systems...System.5..Data.ingestion."    ,
    processing_5 = "Indicate.which.steps.are.handled.by.the.same.system..for.up.to.five.typical.systems...System.5..Data.processing."   ,
    elementary_5 = "Indicate.which.steps.are.handled.by.the.same.system..for.up.to.five.typical.systems...System.5..Elementary.indexes.",
    aggregation_5 = "Indicate.which.steps.are.handled.by.the.same.system..for.up.to.five.typical.systems...System.5..Aggregation."       ,
    finalization_5 = "Indicate.which.steps.are.handled.by.the.same.system..for.up.to.five.typical.systems...System.5..Finalization.",
)
df$ingestion <- rowSums(df[,c("ingestion_1", "ingestion_2", "ingestion_3", "ingestion_4", "ingestion_5")], na.rm=TRUE)
df$processing <- rowSums(df[,c("processing_1", "processing_2", "processing_3", "processing_4", "processing_5")], na.rm=TRUE)
df$elementary <- rowSums(df[,c("elementary_1", "elementary_2", "elementary_3", "elementary_4", "elementary_5")], na.rm=TRUE)
df$aggregation <- rowSums(df[,c("aggregation_1", "aggregation_2", "aggregation_3", "aggregation_4", "aggregation_5")], na.rm=TRUE)
df$finalization <- rowSums(df[,c("finalization_1", "finalization_2", "finalization_3", "finalization_4", "finalization_5")], na.rm=TRUE)

# Overlay all histograms on one plot
dat <- data.frame(
  Frequency = c(df$ingestion, df$processing, df$elementary, df$aggregation, df$finalization),
  Step = c(
    rep("Inegstion", each=nrow(df)),
    rep("Processing", each=nrow(df)),
    rep("Elementary indexes", each=nrow(df)),
    rep("Aggregation", each=nrow(df)),
    rep("Finalization", each=nrow(df))
  )
)

ggplot(dat,aes(x=Frequency, fill=Step)) + geom_histogram(alpha=0.6, position="stack")
```


```{r message = FALSE}
#| label: fig-steps-by-team-type
#| layout-ncol: 2
#| echo: false
#| out-width: "100%"
#| fig-cap:
#| - Steps Handled by Central IT
#| - Steps Handled by Domain-Embedded IT
#| - Steps Handled by Domain-Embedded Analysts
#| - Steps Handled by Analysts Elsewhere in the Organization
#| - Steps Handled by Contractors

df <- read.csv("./data/results.csv")

df <- df |> rename(
  ingestion_c_it = colnames(df)[42],
  processing_c_it = colnames(df)[43],
  elementary_c_it = colnames(df)[44],
  agg_c_it = colnames(df)[45],
  fin_c_it = colnames(df)[46],
  ingestion_d_it = colnames(df)[47],
  processing_d_it = colnames(df)[48],
  elementary_d_it = colnames(df)[49],
  agg_d_it = colnames(df)[50],
  fin_d_it = colnames(df)[51],
  ingestion_d_analyst = colnames(df)[52],
  processing_d_analyst = colnames(df)[53],
  elementary_d_analyst = colnames(df)[54],
  agg_d_analyst = colnames(df)[55],
  fin_d_analyst = colnames(df)[56],
  ingestion_e_analyst = colnames(df)[57],
  processing_e_analyst = colnames(df)[58],
  elementary_e_analyst = colnames(df)[59],
  agg_e_analyst = colnames(df)[60],
  fin_e_analyst = colnames(df)[61],
  ingestion_consultant = colnames(df)[62],
  processing_consultant = colnames(df)[63],
  elementary_consultant = colnames(df)[64],
  agg_consultant = colnames(df)[65],
  fin_consultant = colnames(df)[66]
)

# Corporate IT
dat <- data.frame(
  Frequency = c(df$ingestion_c_it, df$processing_c_it, df$elementary_c_it, df$agg_c_it, df$fin_c_it),
  Step = c(
    rep("Inegstion", each=nrow(df)),
    rep("Processing", each=nrow(df)),
    rep("Elementary indexes", each=nrow(df)),
    rep("Aggregation", each=nrow(df)),
    rep("Finalization", each=nrow(df))
  )
)

# Fill NA with zero
dat[is.na(dat)] = 0

ggplot(dat, aes(x=Step, y=Frequency)) + geom_bar(stat="identity", fill="#dae8fc")

# Domain embedded IT

dat <- data.frame(
  Frequency = c(df$ingestion_d_it, df$processing_d_it, df$elementary_d_it, df$agg_d_it, df$fin_d_it),
  Step = c(
    rep("Inegstion", each=nrow(df)),
    rep("Processing", each=nrow(df)),
    rep("Elementary indexes", each=nrow(df)),
    rep("Aggregation", each=nrow(df)),
    rep("Finalization", each=nrow(df))
  )
)

# Fill NA with zero
dat[is.na(dat)] = 0

ggplot(dat, aes(x=Step, y=Frequency)) + geom_bar(stat="identity", fill="#fff2cc")


# Domain embedded analysts

dat <- data.frame(
  Frequency = c(df$ingestion_d_analyst, df$processing_d_analyst, df$elementary_d_analyst, df$agg_d_analyst, df$fin_d_analyst),
  Step = c(
    rep("Inegstion", each=nrow(df)),
    rep("Processing", each=nrow(df)),
    rep("Elementary indexes", each=nrow(df)),
    rep("Aggregation", each=nrow(df)),
    rep("Finalization", each=nrow(df))
  )
)

# Fill NA with zero
dat[is.na(dat)] = 0

ggplot(dat, aes(x=Step, y=Frequency)) + geom_bar(stat="identity", fill="#fff2cc")

# Elsewhere Analysts
dat <- data.frame(
  Frequency = c(df$ingestion_e_analyst, df$processing_e_analyst, df$elementary_e_analyst, df$agg_e_analyst, df$fin_e_analyst),
  Step = c(
    rep("Inegstion", each=nrow(df)),
    rep("Processing", each=nrow(df)),
    rep("Elementary indexes", each=nrow(df)),
    rep("Aggregation", each=nrow(df)),
    rep("Finalization", each=nrow(df))
  )
)

# Fill NA with zero
dat[is.na(dat)] = 0

ggplot(dat, aes(x=Step, y=Frequency)) + geom_bar(stat="identity", fill="#dae8fc")

# Consultants
dat <- data.frame(
  Frequency = c(df$ingestion_consultant, df$processing_consultant, df$elementary_consultant, df$agg_consultant, df$fin_consultant),
  Step = c(
    rep("Inegstion", each=nrow(df)),
    rep("Processing", each=nrow(df)),
    rep("Elementary indexes", each=nrow(df)),
    rep("Aggregation", each=nrow(df)),
    rep("Finalization", each=nrow(df))
  )
)

# Fill NA with zero
dat[is.na(dat)] = 0

ggplot(dat, aes(x=Step, y=Frequency)) + geom_bar(stat="identity")
```